var model = {
	images: [
		{area: "Capo D'Orlando",img: "CapoDOrlandovandSten.jpg", title: "Vi er lige ankommet til Capo D'Orlando og er meget begejstret for det klare vand.", location: [14.750305, 38.163641]},
		{area: "Capo D'Orlando",img: "EmilBarNumseCapo.JPG", title: "Doven-kravl. ", location: [14.742171, 38.154598]},
		{area: "Capo D'Orlando",img: "EmilToiletCapo.JPG", title: "Og første toiletbesøg efter han begyndte at skide på terassen.", location: [14.742171, 38.154598]},
		{area: "Capo D'Orlando",img: "AMChillCapo.JPG", title: "Sådan her chiller Anne Marie gerne under Emils lurer – får læst dejligt mange bøger.", location: [14.742171, 38.154598]},
		{area: "Capo D'Orlando",img: "zara.jpg", title: "Her er vores skønne udlejer Sara. Giver dagligt Anders instruktioner i indkøb og opskrifter. ", location: [14.742171, 38.154598]},
		{area: "Capo D'Orlando",img: "zara, anders og emil.jpg", title: "Hun er utilfreds med ungdomsarbejdsløsheden, Panama-Papers og Gramsci og Marx stående i bogreolen. Og så kan hun ovenikøbet med en dags varsel skaffe tid hos en frisør lørdag formiddag.", location: [14.742171, 38.154598]},
		{area: "Capo D'Orlando",img: "zara menu.jpg", title: "Sara inviterede på tre retters heavy frokost og gav os rester nok til flere dage.", location: [14.742171, 38.154598]},
		{area: "Capo D'Orlando",img: "CannoliSara.jpg", title: "Desserten var den her Canolli – en Ricotta-bombe", location: [14.742171, 38.154598]},
		{area: "Capo D'Orlando",img: "EMilAndersFrokostCapo.JPG", title: "Frokost ved stranden, der ligger 300 meter fra lejligheden.", location: [14.736952, 38.15585]},
		{area: "Capo D'Orlando",img: "EmilAndersVandreSmilCapo.JPG", title: "Bærestolen afprøves for første gang – stor succes.", location: [14.724, 38.142]},
		{area: "Messina",img: "HavneCafeMessina.JPG", title: "På togtur til Messina. Den første time søger vi ly for regnen på HavneCafeen med byens skævere eksistenser. Vi vender tilbage til aftensmad da toget hjem er to timer forsinket. ", location: [15.547, 38.181]},
		{area: "Messina",img: "CricketMessina.jpg", title: "Vi oplever mange indere i Messina – her fanger vi en gruppe unge cricket-spillere.", location: [15.545, 38.175]},
		{area: "Messina",img: "UdsigtFastlandMessina.JPG", title: "I baggrunden kan fastlandet skimtes. I følge Esters kollega har en bro været planlagt i årtier, men bliver ikke rigtig realiseret.", location: [15.552517, 38.193724]},
		{area: "Capo D'Orlando",img: "Emil flyver Capo.JPG", title: "Emil får flyve…", location: [14.732356, 38.150593]},
		{area: "Capo D'Orlando",img: "EMilGyngeCapo.JPG", title: "...og gyngetur.", location: [14.732356, 38.150593]},
		{area: "Cefalù",img: "AMeMilCefalu.jpg", title: "Venter på frokosten i Cefalu.", location: [14.021, 38.039]},
		{area: "Cefalù",img: "KødCefalu.jpg", title: "Og den var værd at vente på – åndssvagt lækkert kalv.", location: [14.021, 38.039]},
		{area: "Capo D'Orlando",img: "EmilPotteplanteCapo.JPG", title: "Emil er ret doven og bevæger sig kun hvis der er noget rigtig interessant.", location: [14.742171, 38.154598]},
		{area: "Capo D'Orlando",img: "EmilNøgenCapo.JPG", title: "Og så hjælper det at være nøgen.", location: [14.742171, 38.154598]},
		{area: "Capo D'Orlando",img: "GangstaHåndtegnCapo.JPG", title: "Emil kører SWAG durag-style og kaster håndtegn", location: [14.742171, 38.154598]},
		{area: "Capo D'Orlando",img: "GranitaCapo.JPG", title: "Sara har introduceret os til Granita med Panne – mums. ", location: [14.745255, 38.159795]},
		{area: "Capo D'Orlando",img: "OpstigningCapo.JPG", title: "På vandretur til kalkstenstop i en nationalpark tæt på Capo D'Orlando. ", location: [14.735, 38.011]},
		{area: "Capo D'Orlando",img: "TopCapo.JPG", title: "Emil har optur på toppen, mens Anders prøver at fange GPS'en og finde en rute ned igen.", location: [14.735, 38.01]},
		{area: "Capo D'Orlando",img: "EmilBlomsterTop.JPG", title: "I det korte frokosthvil.", location: [14.735, 38.01]},
		{area: "Capo D'Orlando",img: "NedturCapo.JPG", title: "Nedad…", location: [14.733, 38.007]},
		{area: "Capo D'Orlando",img: "Nedtur2capo.JPG", title: "...i lang tid…", location: [14.738, 38.006]},
		{area: "Capo D'Orlando",img: "EmilSoverNedtur.JPG", title: "...så Emil tager en lur.", location: [14.738, 38.006]},
		{area: "Capo D'Orlando",img: "HjemVandfald.JPG", title: "Efter en hviledag tog vi en lidt lettere tur til et vandfald i samme nationalpark.", location: [14.807, 37.998]},
		{area: "Capo D'Orlando",img: "EMilVågnetVandfald.JPG", title: "Emil lige vågnet og kigger omtumlet mod det brusende vandfald.", location: [14.806, 37.997]},
		{area: "Capo D'Orlando",img: "vandfald.JPG", title: "Ser småt ud på billedet med var 7 til 8 meter højt.", location: [14.806, 37.997]},
		{area: "Capo D'Orlando",img: "DelikatessenCapo.JPG", title: "Vores lokale delikatesse-shop.", location: [14.738461, 38.156044]},
		{area: "Capo D'Orlando",img: "StrandMadCapoDOrlando.jpg", title: "Aftensmad indkøbt i delikatessen nydes ved stranden.", location: [14.737, 38.156]},
		{area: "Capo D'Orlando",img: "LegStrandCapo.JPG", title: "Og fordøjes.", location: [14.737, 38.156]},
		{area: "Capo D'Orlando",img: "EmilAndersStrandCapo.JPG", title: "", location: [14.737, 38.156]},
		{area: "Capo D'Orlando",img: "StrandaftenCapo.JPG", title: "", location: [14.737, 38.156]},
		{area: "Palermo",img: "TransportTog.JPG", title: "Så flytter vi fra Capo D'Orlando. Lidt besværlig oppakning til en togtur så vi lejer bil for resten af turen i Palermo. Så kan vi også hente Ester og Gitte i lufthavnen.", location: [13.354074, 38.10892]},
		{area: "Palermo",img: "bil.jpg", title: "Lækkert med stationcar til alt vores lort", location: [13.354074, 38.10892]},
		{area: "Castellammare del Golfo",img: "1gåturCastellammara.JPG", title: "Lige ankommet til vores hus 10 km uden for Castellammare Del Golfo. Aftentur ved kysten uden for vores hoveddør", location: [12.859, 38.048]},
		{area: "Castellammare del Golfo",img: "EsterGiverMad.JPG", title: "Så er Ester og Gitte ankommet. Under deres besøg tog de sig af morgenvagterne og bespisning", location: [12.856, 38.047]},
		{area: "Castellammare del Golfo",img: "Esterskifter.JPG", title: "Og ikke mindst lortebleerne!", location: [12.856, 38.047]},
		{area: "Castellammare del Golfo",img: "GitteEmil.jpg", title: "", location: [12.856, 38.047]},
		{area: "Castellammare del Golfo",img: "EsterGitteAnders.jpg", title: "På vej opad for at nyde udsigten over Castallammare del Golfo", location: [12.87, 38.017]},
		{area: "Castellammare del Golfo",img: "AndersTop.jpg", title: "Anders og Anne Marie kravler helt til tops, mens bedstemødrene giver Emil øllebrød lidt længere nede", location: [12.872, 38.012]},
		{area: "Castellammare del Golfo",img: "Castellammare oppefra.jpg", title: "", location: [12.872, 38.012]},
		{area: "Castellammare del Golfo",img: "CastellammarePynt.jpg", title: "Gåtur i Castallammare Del Golfo. ", location: [12.885, 38.029]},
		{area: "Castellammare del Golfo",img: "CastellammareSjovtHus.jpg", title: "Herligt hus på kanten af havnen.", location: [12.881, 38.028]},
		{area: "Castellammare del Golfo",img: "AndersEmilSkrænt.jpg", title: "Efter tre dages intensivt besøg af damerne havde vi alle tre brug for et par hviledage med turer i nabolaget og mange lurer på skift.", location: [12.863, 38.051]},
		{area: "Castellammare del Golfo",img: "SkræntMflotbudskds.jpg", title: "Vi finder selvfølgeligt forsat mange flotte udsigter i lokalområdet som vi gerne ville have opdaget med Gitte og Ester.", location: [12.863, 38.051]},
		{area: "Castellammare del Golfo",img: "EmilSur.jpg", title: "Bedstemødrerne blev noget chokeret over Emils skrigeri om natten. Han kan dog også være sur om dagen – her prøver vi (uden succes) at aflede ham med tegnefilm mens vi pakker bilen. ", location: [12.856, 38.047]},
		{area: "Castelluzzo",img: "Emilgladpåsten.jpg", title: "Men for det meste er han glad og begejstret over tissemyrer, sten og hans egne hænder.", location: [12.712, 38.105]},
		{area: "Castelluzzo",img: "Emilglad.jpg", title: "", location: [12.712, 38.105]},
		{area: "Castelluzzo",img: "Emilgladnøgen.jpg", title: "", location: [12.712, 38.105]},
		{area: "Castelluzzo",img: "EmilopturBog.JPG", title: "", location: [12.712, 38.105]},
		{area: "Castelluzzo",img: "AndersGriller.JPG", title: "Vi er nu flyttet en lille time længere mod vest til Castelluzzo. Her har vi lejet et skønt hus og er endnu engang omringet af hav og bjerge. Huset er over 100 år gammelt, rumligt og køligt med en overdækket indergård til måltiderne.", location: [12.712, 38.105]},
		{area: "Castelluzzo",img: "UdsigtHavenDag.jpg", title: "Udsigt fra haven dag.", location: [12.7119, 38.1056]},
		{area: "Castelluzzo",img: "UdsigtenFraHaven.jpg", title: "Udsigt fra haven aften.", location: [12.7119, 38.1056]},
		{area: "Castelluzzo",img: "EmilGladMad.jpg", title: "Gitte lærte Emil (og os!) at han selv kan fange maden – og nu vil han helst selv. Måltiderne tager derfor noget længere tid. Men vi har jo heldigvis ikke så travlt.", location: [12.712, 38.105]},
		{area: "Castelluzzo",img: "EmilSpiseBønne.JPG", title: "", location: [12.712, 38.105]},
		{area: "Castelluzzo",img: "EMilKylling.jpg", title: "", location: [12.712, 38.105]},
		{area: "Castelluzzo",img: "AndersModTopCofane.jpg", title: "Her bestiger vi bjerget i baghaven – på under en halv time stiger vi 400 højdemeter.  ", location: [12.704, 38.098]},
		{area: "Castelluzzo",img: "TopSkræntCopane.jpg", title: "Udsigten ned på vores bugt.", location: [12.702, 38.097]},
		{area: "Castelluzzo",img: "Landbrug.jpg", title: "Dagligt smager og nyder vi, at Sicilien er en landbrugsø, men det er nærmest første gang vi ser egentlige marker. Skægt at betragte en bondemand, der med stor præcision trimmede sine oliventræer.", location: [12.698, 38.096]},
		{area: "Castelluzzo",img: "MarmorProduktion.JPG", title: "Fra bjergvæggen udvindes og bearbejdes marmor. ", location: [12.697, 38.095]},
		{area: "Castelluzzo",img: "UdsigtCofaneBugt.jpg", title: "Nedturen mod vores hus.", location: [12.686, 38.105]},
		{area: "Castelluzzo",img: "SletteLandskab.jpg", title: "Landskabet leder tankerne mod heden i Tversted – hvis vi ser bort fra bjerget.", location: [12.71, 38.108]},
		{area: "Castelluzzo",img: "AndersEmilFjernsyn.jpg", title: "Anders lærer Emil at chille til Kung Fu Panda 3.", location: [12.712, 38.105]},
		{area: "Castelluzzo",img: "AndersCykel.jpg", title: "Der hører cykler til huset og på 15 minutter kan vi nå en bager, grønthandler, slagter og købmand. ", location: [12.73, 38.106]},
		{area: "Castelluzzo",img: "AMaftenbadetur.jpg", title: "Aftenbadetur i vores bugt.", location: [12.728, 38.124]},
		{area: "Castelluzzo",img: "BjergTåge.jpg", title: "Dramatisk hjemtursview. ", location: [12.73, 38.116]},
		{area: "Castelluzzo",img: "AndersKoder.JPG", title: "Anders bygger denne hjemmeside i gårdhaven. Han har lige udtrykt stor optur over hans 1000 sider lange opslagsbog om Javascript som er så god underholdning, at han ikke længere er ked af der ikke er net i huset.", location: [12.712, 38.105]},
		{area: "Erice",img: "Erice.jpg", title: "På tur til borg-byen Erice, der ligger i 750 meters højde. ", location: [12.587735, 38.035892]},
		{area: "Erice",img: "UdsigtSaltErice.jpg", title: "Udsigt til Trapani's saltproduktion og områdets marmor brud", location: [12.587735, 38.035892]},
		{area: "Castelluzzo",img: "GrøntVognSanVito.jpg", title: "Indkøb i den nærliggende badeby San Vito Lo Capo", location: [12.734, 38.172]},
		{area: "Castelluzzo",img: "AMCykelTkryds.jpg", title: "Hvilken vej skal vi vælge? Der er smukt i begge retninger.", location: [12.6955, 38.105]},
		{area: "Castelluzzo",img: "AMEmilCornino.jpg", title: "Returgang efter 3-4 timers tur til Cornino. Bag den flade klippe i baggrunden ligger San Vito", location: [12.6626, 38.1113]},
		{area: "Castelluzzo",img: "AMEmilStol.jpg", title: "Høj sol til hjemturen giver energi", location: [12.6585, 38.1041]},
		{area: "Castelluzzo",img: "BjergmedKlipCornino.jpg", title: "Klippe med klippe på", location: [12.6581, 38.1069]},
		{area: "Castelluzzo",img: "ConinoHav.jpg", title: "Sidste kig på bugten ved Cornino på hjemturen", location: [12.6584, 38.1056]},
		{area: "Castelluzzo",img: "CorninoTonnara.jpg", title: "Resterne af ruin forenden af AM's løberute", location: [12.6797, 38.1117]},
		{area: "Castelluzzo",img: "FalleretRestaurant.jpg", title: "Cornino var lidt faldefærdig uden for turistsæsonnen", location: [12.6581, 38.089]},
		{area: "Castelluzzo",img: "frokostCornino.jpg", title: "Men vi fandt en restaurant, der havde åbent. Pasta i boullion gør det godt, når man småfryser og er sulten efter vandretur", location: [12.6574, 38.089]},
		{area: "Castelluzzo",img: "corninobord.jpg", title: "Her kan man også sidde og forfatte bøger", location: [12.6583, 38.0892]},
		{area: "Castelluzzo",img: "marmorBrud.jpg", title: "Endnu en af mange marmorbrud", location: [12.6697, 38.0983]},
		{area: "Castelluzzo",img: "cykelTonnara.jpg", title: "Trækker cyklen det sidste stykke inden vi skal i gang med bjergbestigningen", location: [12.6802, 38.1111]},
		{area: "Castelluzzo",img: "klipperHav.jpg", title: "Skarpe klipper og blåt hav", location: [12.6784, 38.1133]},
		{area: "Castelluzzo",img: "militaerTaarn.jpg", title: "Militært udkigstårn med udsigt over Cornino-bugten", location: [12.6588, 38.1094]},
		{area: "Castelluzzo",img: "tonnaraHus.jpg", title: "", location: [12.686, 38.107]},
		{area: "Castelluzzo",img: "tonnaraRuin.jpg", title: "", location: [12.6797, 38.1117]},
		{area: "Castelluzzo",img: "vildHav.jpg", title: "Hav vs. Klippe – Hav vinder!", location: [12.6661, 38.1124]},
		{area: "Castelluzzo",img: "BugtSanVito.jpg", title: "Vinden stod lige ind i vores bugt og gav lidt mere gang i bølgerne omkring skær", location: [12.678, 38.1078]},
		{area: "San Vito Lo Capo",img: "sanvitostrand1.jpg", title: "Så er der bounty strand i San Vito", location: [12.7362, 38.1763]},
		{area: "San Vito Lo Capo",img: "sanvitostrand3.jpg", title: "Stadig en smule forfriskende", location: [12.7362, 38.1763]},
		{area: "San Vito Lo Capo",img: "sanvitostrand4.jpg", title: "Bjergtoppen oppe i højre hjørne har vi besteget", location: [12.7362, 38.1763]},
		{area: "San Vito Lo Capo",img: "Couscous.jpg", title: "Lækker arabisk inspireret restaurant, men lidt forhastet besøg med træt Emil.", location: [12.7355, 38.1752]},
		{area: "Castelluzzo",img: "Husbaghave.jpg", title: "Vores hus", location: [12.7119, 38.1056]},
		{area: "Castelluzzo",img: "emilPaaHoved.jpg", title: "Så er han underholdt", location: [12.712, 38.105]},
		{area: "Castelluzzo",img: "EmilChill.jpg", title: "Der chilles!", location: [12.712, 38.105]},
		{area: "Castelluzzo",img: "udsigtGaard.jpg", title: "Man bliver tit overrasket når man kigger op og ser bjergmassivet fra gårdhaven", location: [12.712, 38.1053]},
		{area: "Castelluzzo",img: "baghave.jpg", title: "Vores baghave med glimt til havet", location: [12.7119, 38.1056]},
		{area: "Castelluzzo",img: "olivenlund.jpg", title: "Naboens velplejede olivenlund.", location: [12.7119, 38.1056]},
		{area: "Castelluzzo",img: "helnatsoevn.jpg", title: "Så skete det! Emil sov natten mellem 4. og 5. maj igennem for første gang - 11 timer uden at vågne. Sådan ser han ud lige efter opvågning", location: [12.713, 38.1054]},
		{area: "Castelluzzo",img: "VoresSpotSt.JPG", title: "Vi har fundet et lækkert spot i vores bugt. Anders og Emil kan skimtes i ly for solen under klippen. ", location: [12.6933, 38.1055]},
		{area: "Castelluzzo",img: "strandgrotte.jpg", title: "Øllebrød og bølgebrus.", location: [12.6932, 38.1054]},
		{area: "Castelluzzo",img: "emilbader1.jpg", title: "", location: [12.6932, 38.1054]},
		{area: "Castelluzzo",img: "emilbader2.jpg", title: "Og første ”dukkert”.", location: [12.6932, 38.1054]},
		{area: "San Vito Lo Capo",img: "madunderoliven.jpg", title: "Hurtig mad i olivenlund inden opstigning.", location: [12.7395, 38.1551]},
		{area: "San Vito Lo Capo",img: "mamrmormaskine.jpg", title: "Så skal der skubbes sten…", location: [12.747, 38.1538]},
		{area: "San Vito Lo Capo",img: "marmorplade.jpg", title: "...så der kan blive fliser af marmor", location: [12.7467, 38.153]},
		{area: "San Vito Lo Capo",img: "castelluzzobugt.jpg", title: "Vi har taget mange billeder af bugter og bjerge, så I får lige et til.", location: [12.7569, 38.1672]},
		{area: "San Vito Lo Capo",img: "ligsti.jpg", title: "", location: [12.7575, 38.1639]},
		{area: "San Vito Lo Capo",img: "golfo.jpg", title: "Et kig til vores tidligere hjem ved Castellamare del Golfo", location: [12.7571, 38.167]},
		{area: "San Vito Lo Capo",img: "sanvitofraoven.jpg", title: "San Vito fra 500 meters højde", location: [12.7569, 38.1672]},
		{area: "San Vito Lo Capo",img: "ammeudsigt2.jpg", title: "Amning inden nedstigning", location: [12.7569, 38.167]}
	],
	filteredImages: []
};